In [1]:
import pandas as pd
#5.1pandas的数据结果介绍 Series和DataFrame
#Series是一种类似于一维数组的对象，它有一组数据（各种Numpy数据类型）以及一组与之相关的数据标签（即索引）组成
obj=pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [2]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
#通常希望所创建的Series带有一个可以对各个数据点进行标记的索引
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [5]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [6]:
#与普通Numpy数组相比，你可以通过索引的方式选取Series中的单个或一组值
obj2['a']

-5

In [7]:
obj2['d']=6

In [8]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [10]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [11]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
#还可以将Series堪称一个定长的有序字典，因为它是索引值到数据值的一个映射
'b' in obj2

True

In [13]:
'e' in obj2

False

In [14]:
#如果一个数据被存放再一个Python字典中，也可以直接通过这个字典来创建Series
sdata={'Ohio':36000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=pd.Series(sdata)
obj3

Ohio      36000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [15]:
#如果只传入一个字典，则结果Series中的索引就是原字典的键（有序排列）。可以传入排好序的字典的键以改变顺序
states=['California','Ohio','Oregon','Texas']
obj4=pd.Series(sdata,index=states)

In [16]:
obj4

California        NaN
Ohio          36000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
states=['xxx','11','222','3333']
obj4=pd.Series(sdata,index=states)
obj4

xxx    NaN
11     NaN
222    NaN
3333   NaN
dtype: float64

In [18]:
#pandas的isnull和notnull函数可用于检测缺失数据
pd.isnull(obj4)

xxx     True
11      True
222     True
3333    True
dtype: bool

In [19]:
pd.notnull(obj4)

xxx     False
11      False
222     False
3333    False
dtype: bool

In [20]:
#序列也有类似的实例方法
obj4.isnull()

xxx     True
11      True
222     True
3333    True
dtype: bool

In [21]:
#对于许多应用而言，Series最重要的一个功能是，她会根据运算的索引标签自动对齐数据
obj3

Ohio      36000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
obj4

xxx    NaN
11     NaN
222    NaN
3333   NaN
dtype: float64

In [23]:
obj3+obj4

11       NaN
222      NaN
3333     NaN
Ohio     NaN
Oregon   NaN
Texas    NaN
Utah     NaN
xxx      NaN
dtype: float64

In [24]:
#Series对象本身及其索引都有一个name属性，该属性跟pandas其他的关键功能关系非常密切
obj4.name='population'
obj4.index.name='state'
obj4

state
xxx    NaN
11     NaN
222    NaN
3333   NaN
Name: population, dtype: float64

In [25]:
#Series的索引可以通过赋值的方式就地修改
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [26]:
obj.index=['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [27]:
#DataFrame是一个表格型得数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）。DataFrame既有行索引也有列索引
#可以被看做由Series组成的字典（共用同一个索引）。DataFrame中的数据是可以以一个或多个二维快存放的（而不是列表、字典或别扽一维数据结构）
#建DataFrame办法很多，最常用的传入一个由等长列表或NumPy数组组成的字典
data={'state':['Ohio','Ohio','Nevada','Nevada','Nevada','Nevada'],
     'year':[2000,2001,2002,2001,2002,2003],
     'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2  Nevada  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [28]:
#head方法选取前五行
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2  Nevada  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [29]:
#如果指定了列序列，则DataFrame的列就会按照指定顺序进行排列：
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002  Nevada  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [30]:
#如果传入的列再数据中找不到，就会再结果中产生缺失值
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002  Nevada  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [31]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [32]:
#通过类似字典标记的方式或属性的方式，可以将DataFrame的列获取为一个Series
frame2['state']

one        Ohio
two        Ohio
three    Nevada
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [33]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [34]:
#行可以通过位置或名称的方式进行获取，比如loc属性
frame2.loc['three']

year       2002
state    Nevada
pop         3.6
debt        NaN
Name: three, dtype: object

In [35]:
#列可以通过赋值的方式进行修改。例如，我们可以给那个空的‘debt’列赋上一个标量值或一组值
frame2['debt']=16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002  Nevada  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [36]:
frame2['debt']=np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002  Nevada  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [37]:
#将列表或数组赋值给某列时，其长度必须跟DataFrame的长度相匹配。
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt']=val

In [38]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002  Nevada  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [39]:
#为不存在的列赋值会创建出一个新列。关键字del用于删除列
frame2['eastern']=frame2.state=='Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002  Nevada  3.6   NaN    False
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [40]:
#注意，不能用frame2.eastern创建新的列
#del方法可以用来删除这列
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
#注意：通过索引方式返回的列只是相应数据的视图而已，并不是副本。因此，对返回的Series所做的任何就地修改全都会反映到源DataFrame上。
#通过Series的copy方法即可指定复制列
#另一种常见的数据形式是嵌套字典
pop={'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [42]:
#如果嵌套字典传给DataFrame,pandas就会被解释为：外层字典的键作为列，内层的键则作为行索引
frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [43]:
#你也可以使用类似NumPy数组的方法，对DataFrame进行转置（交换行和列）
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [44]:
#内层字典的键会被合并、排序以形成最终的索引。如果明确指定了索引，则不会这样：
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [45]:
#如果设置了DataFrame的index和columns的name属性，则这些信息也会被显示出来
frame3.index.name='year';frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [46]:
#跟Series一样，values属性也会以二维ndarray的形式返回DataFrame中的数据
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [47]:
#如果DataFrame各列的数据类型不同，则值数组的dtype就会用兼容所有列的数据类型
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Nevada', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [48]:
#索引对象
#pandas的索引对象负责管理轴标签和其他元数组，构建Deries或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个idnex
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [49]:
obj.values

array([0, 1, 2], dtype=int64)

In [50]:
index[1:]

Index(['b', 'c'], dtype='object')

In [51]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [52]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [53]:
'Ohio' in frame3.columns

True

In [54]:
2003 in frame3.index

False

In [55]:
#与python集合不同，pandas的index可以包含重复的标签
dup_labels=pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [56]:
#5.2基本功能
#重新索引
#pandas对象的一个重要方法就是reindex，其作用是创建一个新对象，它的数据符合新的索引
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [57]:
#用该Series的reindex将会根据新索引进行重排。如果某个索引值当前不存在，就引入缺失值
obj2=obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [58]:
#对于时间序列这样的有序数据，重新索引时可能需要做一些插值处理。method选项即可达到此目的，例如，用ffill可以实现前后值填充
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [59]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [60]:
#借助DataFrame，reindex可以修改（行）索引和列。只传递一个序列时，会重新索引结果的列
frame=pd.DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [61]:
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [62]:
#列可以用columns关键字重新索引
states=['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [63]:
#丢弃指定轴上的项
#drop方法返回的是一个在指定轴上删除了指定值的新对象
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [64]:
new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [65]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [66]:
#对于DataFrame，可以删除任意轴上的索引值。为了演示，先新建一个DataFrame例子
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','NewYork'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [67]:
#用标签序列调用drop会从行标签（asis 0）删除值
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah       8    9     10    11
NewYork   12   13     14    15

In [68]:
#通过传递axis=1或axis=‘columns’可以删除列的值
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
NewYork    12     14    15

In [69]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
NewYork    12     14

In [70]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [71]:
#许多函数，如drop，会修改Series或DataFrame的大小或形状，可以就地修改对象，不会返回新的对象
obj.drop('c',inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [72]:
#索引、选取和过滤
#Series索引的工作方式类似NumPy数组的索引，只不过Series的索引值不只是整数
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [73]:
obj['b']

1.0

In [74]:
obj[1]

1.0

In [75]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [76]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [77]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [78]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [79]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [80]:
obj['b':'c']=5

In [81]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [82]:
#用一个值或序列对DataFrame进行索引其实就是获取一个或多个列
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colordo','Utah','NewYork'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio       0    1      2     3
Colordo    4    5      6     7
Utah       8    9     10    11
NewYork   12   13     14    15

In [83]:
data['two']

Ohio        1
Colordo     5
Utah        9
NewYork    13
Name: two, dtype: int32

In [84]:
data[['three','one']]

three  one
Ohio         2    0
Colordo      6    4
Utah        10    8
NewYork     14   12

In [85]:
#这种索引方式有几个特殊的情况，首先通过切片或布尔型数组选取数据
data[:2]

one  two  three  four
Ohio       0    1      2     3
Colordo    4    5      6     7

In [86]:
data[data['three']>5]

one  two  three  four
Colordo    4    5      6     7
Utah       8    9     10    11
NewYork   12   13     14    15

In [87]:
#另一种用法是通过布尔型DataFrame进行索引
data<5

one    two  three   four
Ohio      True   True   True   True
Colordo   True  False  False  False
Utah     False  False  False  False
NewYork  False  False  False  False

In [88]:
data[data<5]=0

In [89]:
data

one  two  three  four
Ohio       0    0      0     0
Colordo    0    5      6     7
Utah       8    9     10    11
NewYork   12   13     14    15

In [90]:
#用loc和iloc进行选取
#对于DataFrame的行的标签索引，用轴标签（loc）或整数索引 iloc，从而DataFrame选择行和列的子集
data.loc['Colordo',['two','three']]

two      5
three    6
Name: Colordo, dtype: int32

In [91]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [92]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [93]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colordo     7    0    5
Utah       11    8    9

In [94]:
#这两个索引函数也适用于一个标签或多个标签的切片
data.loc[:'Utah','two']

Ohio       0
Colordo    5
Utah       9
Name: two, dtype: int32

In [95]:
data.iloc[:,:3][data.three>5]

one  two  three
Colordo    0    5      6
Utah       8    9     10
NewYork   12   13     14

In [96]:
#整数索引
#算数运算和数据对齐
#pandas最重要的一个功能是，它可以对不同索引的对象进行算数运算，在将对象相加时，如果存在不同的索引对，
#则结果的索引就是该索引对的并集。对于有数据库经验的用户，这就像在索引标签上进行自动外连接
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [97]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [98]:
#将他们相加起来就会产生：
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [99]:
#自动的数据对齐操作在不重叠的索引处引入了Na值。缺失值会在算术运算过程中传播
#对于DataFrame，对齐操作会同事发生在行和列上:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [100]:
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [101]:
#把他们相加后将会返回一个新的DataFrame，其索引和列原来那两个DataFrame的并集
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [102]:
df1=pd.DataFrame({'A':[1,2]})
df2=pd.DataFrame({'B':[3,4]})
df1

A
0  1
1  2

In [103]:
df2

B
0  3
1  4

In [104]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [105]:
#在算术方法中填充值
#在对不同索引的对象进行算术运算时，可能希望当一个对象中某个轴标签在另一个对象中找不到时填充一个特殊值（比如0）
df1=pd.DataFrame(np.arange(12.).reshape(3,4),columns=list('abcd'))
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
df2.loc[1,'b']=np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [106]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [107]:
#将他们相加时，没有重叠的位置就会产生NA值
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [108]:
#使用df1的add方法，传入df2以及一个fill_value参数
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [109]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [110]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [111]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [112]:
#DataFrame和Series之间的运算
#跟不同维度的Numpy数组一样，DataFrame和Series之间算术运算也是有明确规定的
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [113]:
arr[0]

array([0., 1., 2., 3.])

In [114]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [115]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [116]:
#当我们从arr减去arr[0],每一行都会执行这个操作。这就叫广播
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
series=frame.iloc[0]

In [117]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [118]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [119]:
#默认情况下，DataFrame和Series之间的算术运算将Series的索引匹配到DataFrame的列，然后沿着行一直向下广播
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [120]:
#如果某个索引值在DataFrame的列或Series的索引中找不到，则参与运算的两个对象就会被重新索引以形成并集
series2=pd.Series(range(3),index=['b','e','f'])
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [121]:
series3=frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [122]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [123]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [124]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [125]:
#函数应用和映射
#Numpy的ufuncs（元素级数组方法）也可用于操作pandas对象
frame=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -1.232746 -1.234249 -0.976176
Ohio   -0.162034 -0.595118  1.217153
Texas   2.147559 -0.179641 -0.726471
Oregon  1.463971 -1.711717 -0.166742

In [126]:
np.abs(frame)

b         d         e
Utah    1.232746  1.234249  0.976176
Ohio    0.162034  0.595118  1.217153
Texas   2.147559  0.179641  0.726471
Oregon  1.463971  1.711717  0.166742

In [127]:
#另一种常见操作是，将函数应用到由各列或行所形成的一维数组上
#DataFrame的apply方法即可实现此功能
f=lambda x:x.max()-x.min()
frame.apply(f)

b    3.380306
d    1.532076
e    2.193328
dtype: float64

In [128]:
#这里的函数f，计算了一个Series的最大值和最小值的差
frame.apply(f,axis='columns')

Utah      0.258073
Ohio      1.812271
Texas     2.874030
Oregon    3.175687
dtype: float64

In [129]:
#许多最为常见的数组统计功能，都被实现成DataFrame的方法（如sum和mean）
#传递到apply的函数不是必须返回一个标量，还可以返回由多个值组成的Series
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b         d         e
min -1.232746 -1.711717 -0.976176
max  2.147559 -0.179641  1.217153

In [130]:
#元素级的Python函数也是可以用的
format=lambda x:'%.2f'% x
frame.applymap(format)

b      d      e
Utah    -1.23  -1.23  -0.98
Ohio    -0.16  -0.60   1.22
Texas    2.15  -0.18  -0.73
Oregon   1.46  -1.71  -0.17

In [131]:
frame['e'].map(format)

Utah      -0.98
Ohio       1.22
Texas     -0.73
Oregon    -0.17
Name: e, dtype: object

In [132]:
#排序和排名
#可使用sort_index方法，它将返回一个已排序的新对象
obj=pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [133]:
#对于DataFrame，则可以根据任意一个轴上的索引进行排序
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [134]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [135]:
#若要按值对Series进行排序，可使用其sort_values方法
obj=pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [136]:
#在排序时，任何缺失值默认都会被放到Series的末尾
obj=pd.Series([4,np.nan,7,np.nan,-3,2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [137]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [138]:
#当排序一个DataFrame时，你可能希望根据一个或多个列中的值进行排序，将一个或多个列的名字传递给sort_values的by选项即可达到该目的
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [139]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [140]:
#多列排序，传入名称的列表即可
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [141]:
obj=pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [142]:
#也可以根据值在原数据中出现的顺序给出排名
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [143]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [144]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [145]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [146]:
#带有重复标签的轴索引
obj=pd.Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [147]:
#索引的is_unique属性可以告诉你它的值是否时唯一的
obj.index.is_unique

False

In [148]:
#对于带有重复值的索引，数据选取的行为将会有些不同。如果某个索引对应多个值，则返回一个Series，而对应单个值得，则返回一个标量值
obj['a']

a    0
a    1
dtype: int64

In [149]:
obj['c']

4

In [150]:
df=pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])
df

0         1         2
a -1.024464 -0.771895 -0.015375
a -2.124376  1.531009 -2.004200
b  0.082799 -0.671438 -0.882657
b  0.804040 -0.340958 -0.171542

In [151]:
df.loc['b']

0         1         2
b  0.082799 -0.671438 -0.882657
b  0.804040 -0.340958 -0.171542

In [152]:
#5.3汇总和计算描述统计
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [153]:
#调用DataFrame得sum方法将会返回一个含有列得和的Series
df.sum()

one    9.25
two   -5.80
dtype: float64

In [154]:
#传入axis='columns'或axis=1将会按行求和运算
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [155]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [156]:
#对于非数值型数据，describe会产生另外一种汇总统计
obj=pd.Series(['a','a','b','c']*4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [157]:
#相关系数与协方差
import pandas_datareader.data as web
all_data={ticker:web.get_data_yahoo(ticker)
         for ticker in ['AAPL','IBM','MSFT','GOOG']}
price=pd.DataFrame({ticker:data['Adj Close']
                   for ticker,data in all_data.items()})
valume=pd.DataFrame({ticker:data['Volume']
                    for ticker,data in all_data.items()})

In [158]:
#现在计算价格得百分数变化
returns=price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-05-08  0.000197  0.002616 -0.000080 -0.006669
2019-05-09 -0.010744 -0.007626 -0.000080 -0.003335
2019-05-10 -0.013853 -0.000148  0.012988  0.001626
2019-05-13 -0.058119 -0.028821 -0.029733 -0.027691
2019-05-14  0.015830  0.014381  0.011188 -0.010238

In [159]:
returns['MSFT'].corr(returns['IBM'])

0.48689305372314945

In [160]:
returns['MSFT'].cov(returns['IBM'])

8.679687515247442e-05

In [162]:
#Series的corr方法用于计算两个Series中重叠的、非NA的、按索引对齐的值的相关系数。
#码到214
returns.MSFT.corr(returns.IBM)

0.48689305372314945

In [163]:
#另一方面，DataFrame的corr和cov方法将以DataFrame的形式分别返回完整的相关系数或协方差矩阵
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.373101  0.449943  0.456660
IBM   0.373101  1.000000  0.486893  0.404023
MSFT  0.449943  0.486893  1.000000  0.534783
GOOG  0.456660  0.404023  0.534783  1.000000

In [164]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000271  0.000076  0.000107  0.000116
IBM   0.000076  0.000152  0.000087  0.000077
MSFT  0.000107  0.000087  0.000209  0.000119
GOOG  0.000116  0.000077  0.000119  0.000238

In [165]:
#利用DataFrame的corrwith方法，你可以计算其列或行跟另一个Series或DataFrame之间的相关系数。传入一个Series将会返回一个相关系数值Series（针对各列进行计算）
returns.corrwith(returns.IBM)

AAPL    0.373101
IBM     1.000000
MSFT    0.486893
GOOG    0.404023
dtype: float64

In [167]:
#传入一个DataFrame则会计算按列名配对的相关系数，这里，计算百分比变化与成交量的相关系数
returns.corrwith(valume)

AAPL   -0.059619
IBM    -0.155949
MSFT   -0.089507
GOOG   -0.019904
dtype: float64

In [168]:
#唯一值、值计数以及成员资格
obj=pd.Series(['c','a','d','a','a','b','b','c','c'])
uniques=obj.unique()

In [169]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [170]:
#返回的唯一值事未排序的，如果需要的话，可以对结果再次进行排序（uniques.sort()）
#value_counts用于计算一个Series中各值出现的频率
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [171]:
#isin用于判断矢量化集合的成员资格，可用于过滤Series中或DataFrame列中数据的子集
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [172]:
mask=obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [173]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [174]:
#与isin类似的是Index.get_indexer方法，它可以给你一个索引数组，从可能包含重复值的数组到另一个不同值得数组
to_match=pd.Series(['c','a','b','b','c','a'])
unique_vals=pd.Series(['c','b','a'])
pd.Index(unique_vals).get_indexer(to_match)


array([0, 2, 1, 1, 0, 2], dtype=int64)

In [175]:
#有时希望得到DataFrame中多个相关列得一张柱状图
data=pd.DataFrame({'Qu1':[1,3,4,3,4],
                  'Qu2':[2,3,1,2,3],
                  'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [176]:
#将pandas.value_counts传给该DataFrame的apply函数，就会出现
result=data.apply(pd.value_counts).fillna(0)

In [177]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [ ]:
#5.4总结
#下一章，将会讨论用pandas读取或加载和写入数据集的工具